#ifndef INCLUDE_MCAL_DIO_DIO_CONFIG_H_
#define INCLUDE_MCAL_DIO_DIO_CONFIG_H_

#define PORTA_PIN0_DIRECTION 0
#define PORTA_PIN1_DIRECTION 0
#define PORTA_PIN2_DIRECTION 1
#define PORTA_PIN3_DIRECTION 0
#define PORTA_PIN4_DIRECTION 0
#define PORTA_PIN5_DIRECTION 0
#define PORTA_PIN6_DIRECTION 0
#define PORTA_PIN7_DIRECTION 1

#define PORTB_PIN0_DIRECTION 1
#define PORTB_PIN1_DIRECTION 1
#define PORTB_PIN2_DIRECTION 1
#define PORTB_PIN3_DIRECTION 1
#define PORTB_PIN4_DIRECTION 1
#define PORTB_PIN5_DIRECTION 1
#define PORTB_PIN6_DIRECTION 1
#define PORTB_PIN7_DIRECTION 1

#define PORTC_PIN0_DIRECTION 1
#define PORTC_PIN1_DIRECTION 1
#define PORTC_PIN2_DIRECTION 1
#define PORTC_PIN3_DIRECTION 1
#define PORTC_PIN4_DIRECTION 1
#define PORTC_PIN5_DIRECTION 1
#define PORTC_PIN6_DIRECTION 1
#define PORTC_PIN7_DIRECTION 1

#define PORTD_PIN0_DIRECTION 1
#define PORTD_PIN1_DIRECTION 1
#define PORTD_PIN2_DIRECTION 1
#define PORTD_PIN3_DIRECTION 1
#define PORTD_PIN4_DIRECTION 1
#define PORTD_PIN5_DIRECTION 1
#define PORTD_PIN6_DIRECTION 1
#define PORTD_PIN7_DIRECTION 0

#define PORTA_PIN0_VALUE 0
#define PORTA_PIN1_VALUE 0
#define PORTA_PIN2_VALUE 0
#define PORTA_PIN3_VALUE 0
#define PORTA_PIN4_VALUE 0
#define PORTA_PIN5_VALUE 0
#define PORTA_PIN6_VALUE 0
#define PORTA_PIN7_VALUE 0

#define PORTB_PIN0_VALUE 0
#define PORTB_PIN1_VALUE 0
#define PORTB_PIN2_VALUE 0
#define PORTB_PIN3_VALUE 0
#define PORTB_PIN4_VALUE 0
#define PORTB_PIN5_VALUE 0
#define PORTB_PIN6_VALUE 0
#define PORTB_PIN7_VALUE 0

#define PORTC_PIN0_VALUE 0
#define PORTC_PIN1_VALUE 0
#define PORTC_PIN2_VALUE 0
#define PORTC_PIN3_VALUE 0
#define PORTC_PIN4_VALUE 0
#define PORTC_PIN5_VALUE 0
#define PORTC_PIN6_VALUE 0
#define PORTC_PIN7_VALUE 0

#define PORTD_PIN0_VALUE 0
#define PORTD_PIN1_VALUE 0
#define PORTD_PIN2_VALUE 0
#define PORTD_PIN3_VALUE 0
#define PORTD_PIN4_VALUE 0
#define PORTD_PIN5_VALUE 0
#define PORTD_PIN6_VALUE 0
#define PORTD_PIN7_VALUE 0

#endif

